services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env

  # android:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile.android
  #   container_name: sonhai-android
  #   volumes:
  #     - ./dist:/output